### ISSUE TITLE
AUR

### ISSUE THREAD

**Issue by hockeymikey** [Asuranceturix/adobe-reader-11#1]
This works pretty good. Should publish it on AUR.

**Comment by Asuranceturix** [comment]
Yes, that was always my intention but I never got around to actually do it. Anyhow, I'm glad you found it useful, I've just pushed it to the AUR: https://aur.archlinux.org/packages/adobe-reader-11

**Comment by hockeymikey** [comment]
It was a life saver for a form I had to do, so glad you created it and decided to share it so others can hopefully find use in it also.

**Comment by Asuranceturix** [comment]
Yes, some PDFs sadly work only with Adobe, plus I was unable to find any sane tool to insert visible digital signatures with certificates on Linux.
